version: '3.4'
services:
  db:
    image: mariadb:latest
    ports:
      - 3306:3306
    healthcheck:
      test: "exit 0"
    volumes:
      - ./db/data_dump:/var/lib/mysql
      - ./db/sql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_USER=maria
      - MYSQL_PASSWORD=pass
      - MYSQL_ROOT_PASSWORD=root

  py-srv:
    build:
      context: py-srv
    ports:
      - 80:8000
    healthcheck:
      test: "exit 0"
    command: sh -c "/wait && python app.py"
    environment:
      - WAIT_HOSTS=db:3306
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    depends_on:
      - db
    links:
      - "db:db"
 
  py-test-srv-pytest:
    build: py-test-srv/pytest
    healthcheck:
      test: "exit 0"
    command: sh -c "/wait && pytest -v -s --alluredir=/app/allure-report"
    environment:
      - WAIT_HOSTS=db:3306
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    depends_on:
      - db
    links:
      - "db:db"
    volumes:
     - ./reports:/app/allure-report
   
  py-test-srv-testify:
    build:
      context: py-test-srv/testify
    command: sh -c "/wait && python app.py"
    environment:
      - WAIT_HOSTS=db:3306,py-srv:8000
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    depends_on:
      - py-srv
    links:
      - "py-srv:py-srv"
